import {memo,useCallback,useEffect,useMemo,useState} from 'react';
import {FlatList,Image,Modal,StyleSheet,Text,View} from 'react-native';
import RNFS from 'react-native-fs';
import Ionicons from 'react-native-vector-icons/Ionicons';
import type {ConnectionSettings,HaEntity} from '../../types/homeAssistant';
import {authHeaders,cameraSnapshotUrl} from '../../api/homeAssistant';
import {colors} from '../../theme';
import {i18n} from '../../i18n';
import {CameraPlayer} from './CameraPlayer';
import { PressableScale } from '../../components/PressableScale';

type Props={cameras:HaEntity[];settings:ConnectionSettings;states:HaEntity[]};
const CameraTile=memo(function CameraTile({camera,settings,onOpen}:{camera:HaEntity;settings:ConnectionSettings;onOpen:()=>void}){const token=typeof camera.attributes.access_token==='string'?camera.attributes.access_token:undefined;const remote=cameraSnapshotUrl(settings,camera.entity_id,Date.now(),token);const file=`${RNFS.CachesDirectoryPath}/camera-${camera.entity_id.replace(/\W/g,'_')}.jpg`;const[uri,setUri]=useState(remote);useEffect(()=>{let active=true;void RNFS.downloadFile({fromUrl:remote,toFile:file,headers:token?{}:authHeaders(settings)}).promise.then(r=>{if(active&&r.statusCode>=200&&r.statusCode<300)setUri(`file://${file}`)}).catch(async()=>{if(active&&await RNFS.exists(file))setUri(`file://${file}`)});return()=>{active=false}},[camera.entity_id,settings.baseUrl,settings.token,settings.snapshotRefreshSeconds]);return <PressableScale style={s.tile} onPress={onOpen}><Image source={{uri,headers:uri.startsWith('file:')?undefined:authHeaders(settings)}} style={s.image} onError={()=>void RNFS.exists(file).then(exists=>{if(exists)setUri(`file://${file}`)})}/><View style={s.overlay}><View style={s.liveIcon}><Ionicons name="play" size={16} color="#fff"/></View><Text style={s.name} numberOfLines={1}>{String(camera.attributes.friendly_name??camera.entity_id)}</Text></View></PressableScale>});
export function CameraBrowser({cameras,settings,states}:Props){const[selected,setSelected]=useState<HaEntity|null>(null);const renderItem=useCallback(({item}:{item:HaEntity})=><CameraTile camera={item} settings={settings} onOpen={()=>setSelected(item)}/>,[settings]);const empty=useMemo(()=><View style={s.empty}><Text style={s.emptyText}>{i18n.t('noSelectedCameras')}</Text></View>,[]);return <><FlatList data={cameras} keyExtractor={x=>x.entity_id} renderItem={renderItem} contentContainerStyle={s.list} ListEmptyComponent={empty} initialNumToRender={6} maxToRenderPerBatch={6} windowSize={5}/><Modal visible={!!selected} animationType="fade" onRequestClose={()=>setSelected(null)} statusBarTranslucent>{selected?<CameraPlayer camera={selected} settings={settings} states={states} title={String(selected.attributes.friendly_name??selected.entity_id)} onClose={()=>setSelected(null)}/>:null}</Modal></>}
const s=StyleSheet.create({list:{padding:16,gap:14},tile:{borderRadius:20,overflow:'hidden',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},image:{width:'100%',aspectRatio:16/9,backgroundColor:colors.black},overlay:{position:'absolute',left:0,right:0,bottom:0,padding:14,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:'rgba(0,0,0,.55)'},liveIcon:{width:32,height:32,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:colors.primary},name:{color:'#fff',fontWeight:'800',fontSize:16,flex:1},empty:{padding:24,backgroundColor:colors.surface,borderRadius:18},emptyText:{color:colors.muted}});
